### ISSUE TITLE
SOLVE MINOR ISSUES #1

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#18]
Solve these minor issues:
- [x] Add Social Media Links
     Facebook: https://www.facebook.com/craftsmen.gdsc.iem/
     Instagram: https://www.instagram.com/craftsmen_gdsc/
     Twitter: https://twitter.com/CraftsmanO/
     Github: https://github.com/Diversion2k22/craftsmen
- [x] Improve the colour of the button of Slider
- [x] Improve Categories Component; align it perfectly, it's looking like it's under the Slider

**Comment by kanisht09** [comment]
I have done the third task @rohan26062001
