### ISSUE TITLE
Improve CHECKOUT Page

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#28]

**Comment by rohan26062001** [comment]
Try to build like this:<br>
![image](https://user-images.githubusercontent.com/74822378/156910242-690fb89a-6c68-4e7e-add2-ba88acd6e8b5.png)

@aritrasen2121 and @SBasu-7870 work on this issue

**Comment by rohan26062001** [comment]
@kanisht09 Make changes to the Checkout.jsx and Checkout.css files in the client/src/pages folder

**Comment by kanisht09** [comment]
> @kanisht09 Make changes to the Checkout.jsx and Checkout.css files in the client/src/pages folder

ok bro

**Comment by rohan26062001** [comment]
@Vivek-kumar21 , make this page responsive; Deadline: Tomorrow 12 am

**Comment by rohan26062001** [comment]
@HimaghnaDas , make this page responsive; Deadline: Today 2 pm
