### ISSUE TITLE
ADD PRODUCTS to Commerce.js API

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#31]
@Vivek-kumar21 and @HimaghnaDas this is the most simple task. As you guys are beginners I'm assigning this easy work to you. You have to add data for our Products.jsx Page.

### Step 1
- Go to this website: https://dashboard.chec.io/
### Step 2
- Log in using Craftsmen's official Email and Password. Please find it in the description of our WhatsApp Group.
### Step 3
- After logging in see the sidebar of the page. There you'll find the `Products`.  After expanding click on the `Products`.
### Step 4
- There add products for each category.
- 
![image](https://user-images.githubusercontent.com/74822378/155886257-d3e4696b-c7ef-4cb2-8b1c-0792fa6e54e1.png)
- 
![image](https://user-images.githubusercontent.com/74822378/155886295-935a1900-f52d-46b4-bdce-8dff8666075c.png)

This job requires no coding skills. I'll expect you to complete this job by 28th Feb.

**Comment by rohan26062001** [comment]
@HimaghnaDas @Vivek-kumar21 start working!!!

**Comment by HimaghnaDas** [comment]
Finished

**Comment by vivek-kumar21** [comment]
Finished

**Comment by rohan26062001** [comment]
Good @HimaghnaDas @Vivek-kumar21
