### ISSUE TITLE
Fix Minor Issues

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#35]
- [x] Resolve Navbar Issues
 - [x] Slider Updated
 - [x] Lower the Gap Between the Heading and Product Cards in Homepage
 - [x] Unresponsiveness Fix
 - [x] Console Errors Fix
 - [x] Fix the errors of Console
 - [x] Make Navbar Links Working
 - [x] Product Details Page Minor Change
 - [x] Cart Page Padding
 - [x] Persisted Reducer Implemented

**Comment by rohan26062001** [comment]
@kanisht09 Please try to get this work done by 9th of March

**Comment by kanisht09** [comment]
@rohan26062001  4th and 5th point needs some discussion , 3rd task done .
