### ISSUE TITLE
Improve IMAGE SLIDER

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#4]
Improve the image slider.
Take help from these sources:

- https://codepen.io/panfilov/full/GogJVy/
- https://codepen.io/MergimUjkani/full/awONge/
- https://codepen.io/tylernj42/full/LEKedz/
- https://codepen.io/mrspok407/full/bwLwvL/
- https://codepen.io/suez/full/WvaKpy/
- https://codepen.io/alexnoz/full/brazWd/
- **https://codepen.io/digistate/full/aEqzBB/** 
- **https://codepen.io/johnblazek/full/nxgVPR/** 

Take inspiration from these sliders and try to implement them

**Comment by Rahul-Roy-21** [comment]
Done bro #12
