### ISSUE TITLE
Improve TYPOGRAPHY of Every Page

### ISSUE THREAD

**Issue by rohan26062001** [Diversion2k22/craftsmen#5]
Change the TYPOGRAPHY of every page with fonts that suits the most

**Comment by akshad113** [comment]
hello can you explain how i contribute to open source. can you show me the way around!

**Comment by rohan26062001** [comment]
Hey @akshad113 , ping me here: https://www.linkedin.com/in/rohan-das-3423a5184/

**Comment by Rahul-Roy-21** [comment]
@kanisht09 @rohan26062001 , some of my suggestions for the typography are **_Merienda_**/**_Poppins_** for headers and _**Montserrat**_ for other general,  used them in ImgSlider

[https://fonts.google.com/specimen/Merienda](url)
[https://fonts.google.com/specimen/Montserrat](url)
[https://fonts.google.com/specimen/Poppins](url)

**Comment by kanisht09** [comment]
@Rahul-Roy-21 as far as the slidebar is concerned , the typography which u choose was perfect , and for navbar and footer we can decide the typography now because they are the components which are ready till yet and then maybe we can decide the typography based on the content (later).

**Comment by HimaghnaDas** [comment]
can i contribute here

**Comment by rohan26062001** [comment]
Yes, @HimaghnaDas you can contribute here. @HimaghnaDas and @Vivek-kumar21 , you both will solve this issue. If you face any kind of problem ping us in the whatsapp group.
